# Generated by Django 4.1.7 on 2023-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="image",
            field=models.ImageField(upload_to="test/images/"),
        ),
    ]
