# Generated by Django 4.1.7 on 2023-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0002_alter_test_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorrequest",
            name="doctor_phone",
            field=models.CharField(default=99999999, max_length=50),
            preserve_default=False,
        ),
    ]
