# Generated by Django 4.1.7 on 2023-05-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0003_doctorrequest_doctor_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="response", name="user",),
    ]
