# Generated by Django 4.1.7 on 2023-05-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0004_remove_response_user"),
    ]

    operations = [
        migrations.DeleteModel(name="DoctorRequest",),
    ]
