# Generated by Django 4.1.7 on 2023-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0005_delete_doctorrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="image",
            field=models.ImageField(
                upload_to="test/<django.db.models.fields.CharField>/"
            ),
        ),
    ]
