# Generated by Django 4.1.7 on 2023-05-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0006_alter_test_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactmessage", name="user_id",),
    ]
