# Generated by Django 4.1.7 on 2023-05-30 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0007_remove_contactmessage_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
