# Generated by Django 4.1.7 on 2023-05-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
