# Generated by Django 4.1.7 on 2023-05-27 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_alter_appuser_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="followers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
