# Generated by Django 4.1.7 on 2023-05-27 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_appuser_followers"),
    ]

    operations = [
        migrations.RemoveField(model_name="appuser", name="followers",),
        migrations.AddField(
            model_name="appuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
