# Generated by Django 4.1.7 on 2023-05-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_remove_appuser_followers_appuser_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser", old_name="followers", new_name="contacted_users",
        ),
    ]
