# Generated by Django 4.1.7 on 2023-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0006_alter_appuser_contacted_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="appuser", name="number",),
        migrations.AddField(
            model_name="appuser",
            name="degree",
            field=models.ImageField(
                blank=True, null=True, upload_to="pics/{id}/degree image/"
            ),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="profil_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pics/<django.db.models.fields.AutoField>/profil image/",
            ),
        ),
    ]
